# -*- coding: utf-8 -*-
"""Two_String functions.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cox2FDeKz0vuJzAEC_gVzghdub1S8MT_
"""



"""# String and numeric functions

Exercise 1

Create a variable with a number as a string:

Check its type

Convert it to a string again (even if it already is)

Print the type before and after
"""

variable = "data"
print(type(variable))
string = str(variable)
print(type(string))

"""Exercise 2

Ask the user for their age using input()

Convert it to a string

Print a sentence that includes the age
"""

age = input("whats your age? ")
print("your age is", str(age))
print(f"you are {age} years old")

"""🟢 SECTION 2: Length & Count
Exercise 3

Create this string:

"I love python"


Print the total number of characters

Count how many times "o" appears
"""

word = "I love python"
word_length = len(word)
print("the word lenght is", word_length)
count_o = word.count("o")
print("the number of o's in the word is", count_o)

"""Exercise 4

Ask the user to enter a word

Print the length of the word

Print how many times the letter "a" appears
"""

word = "I love python"
word_length = len(word)
print("the word lenght is", word_length)
count_o = word.count("o")
print("the number of o's in the word is", count_o)

"""🟢 SECTION 3: Transformations

Exercise 5 (Concatenation)

Create two strings:

first name

last name

Join them to form a full name with a space in between and print it.
"""

firstname = input("enter your firstnane:")
lastname = input("enter your lasname: ")
print("your name is" firstbame + "")

"""Exercise 6 (Repetition)

Create this string:

"ha"


Print it repeated 5 times
"""

stuff = "ha"

print ( stuff * 5)

"""Exercise 7 (replace)

Create:

"I like Java"


Replace "Java" with "Python"

Print the result
"""

create = "I like Java"
print(create)
replace = create.replace("Java", "Python")
print(replace)

"""Exercise 8 (split)

Create:

"apple,banana,orange"


Split the string using ,

Print the result
"""

create = "apple,banana,orange"
print(create)
split = create.split(',')
print(split)

"""Exercise 9 (f-string)

Ask the user for:

name

country

Print a sentence using f-string:

My name is ___ and I live in ___
"""

name = input("your name: ")
country = input("your country: ")

print(f"My name is {name} and I live in {country}.")

"""🟢 SECTION 4: Cleaning (Whitespace)
Exercise 10

Create this string (with spaces):

"   python   "


Remove spaces from the left

Remove spaces from the right

Remove spaces from both sides

Print each result.
"""

space = " python  "
print (len(space))
print(space.lstrip())
print (len((space.lstrip())))
print(space.rstrip())
print (len((space.rstrip())))
print(space.strip())
print (len((space.strip())))

"""🟢 SECTION 5: Cleaning (Case) Exercise 12

Create:

"PyThOn"

Convert to lowercase

Convert to uppercase

Print both
"""

word = "PyThOn"
print(word.lower())
print(word.upper())

"""Exercise 13

Ask the user to enter their name

Convert it to uppercase

Print it

🟢 SECTION 6: Extraction (Indexing & Slicing)
Exercise 14

Create:

"python"


Print the first character

Print the last character

Extract "pyt"

Extract "tho"
"""



"""🟢 FINAL MINI-CHALLENGE (uses only what you learned)
Exercise 17

Ask the user for a sentence
Then:

Print the sentence in lowercase

Print the sentence in uppercase

Print the length of the sentence

Remove extra spaces at the beginning and end

## Structured learning approach

Goal: wake up your brain + fingers

Create 2 string variables

Print them

Check their types using type()

✅ Outcome: you’re comfortable creating and printing strings.
"""



"""⏱️ 5 – 15 minutes | Length & Count

Exercises:

Create a sentence of your choice

Print its length

Count how many times a letter appears

Ask the user for a word

Print the word length

Count one letter inside it

🧠 Focus: len(), count()

"""



"""⏱️ 15 – 25 minutes | Transformations (Building strings)

Exercises:

Join first name + last name

Repeat a word multiple times

Replace one word with another

Split a comma-separated string

🧠 Focus: replace() ;; split()
"""



"""⏱️ 25 – 35 minutes | Formatting & f-strings

Exercises:

Ask for name and age

Print a full sentence using f-string

Print another sentence using normal concatenation

🧠 Focus:

Clean, readable output

Understanding how strings are combined
"""



"""⏱️ 35 – 45 minutes | Cleaning Strings

Whitespace

Create a string with extra spaces

Use:

lstrip()

rstrip()

strip()

Case
3. Convert a string to lowercase
4. Convert the same string to uppercase

🧠 Focus:

Cleaning user input

Understanding why this matters
"""



"""⏱️ 45 – 55 minutes | Extraction (Index & Slice)

Exercises:

Create a word ("python")

Print:

first letter

last letter

Slice:

first 3 letters

middle letters

Ask user for a word and extract:

first character

last character

🧠 Focus:

Index positions

Slicing ranges
"""



"""⏱️ 55 – 60 minutes | Mini-Challenge (No stress)

In one script:

Ask the user for a sentence

Print:

lowercase version

uppercase version

length

cleaned (no leading/trailing spaces)

🧠 Focus:

Combining everything you learned

## Strings search and validation (structured learning)

0 – 5 min | Warm-up (Strings & Types)

Create a string variable

Print it

Print its type

Convert it to string again using str()

⏱️ 5 – 15 min | Cleaning (Whitespace + Case)
Exercises

Create a string with spaces at both ends

Apply lstrip()

Apply rstrip()

Apply strip()

Create a mixed-case string

Convert to lowercase

Convert to uppercase

🧠 Goal: understand how text is normalized

⏱️ 15 – 25 min | Length, Count & Extraction
Exercises

Create a sentence

Print its length

Count one letter

Extract:

first character

last character

a slice of characters

🧠 Goal: know how to inspect strings

⏱️ 25 – 35 min | Transformations & Formatting
Exercises

Join first name + last name

Repeat a word 3 times

Replace one word in a sentence

Use an f-string to print a sentence

🧠 Goal: create readable output

⏱️ 35 – 45 min | 🔍 Search in Strings (NEW)
Exercises
Exercise 1: startswith

Create:

"python programming"


Check if it starts with "python"

Print the result

Exercise 2: endswith

Using the same string:

Check if it ends with "programming"

Print the result

Exercise 3: find

Create:

"I love python"


Find the position of "python"

Print the result

👉 Observe:

number ≥ 0 → found

-1 → not found

Exercise 4: in

Check if:

"a" is in "cat"

"z" is in "cat"

Print the results.

🧠 Goal: searching without decisions

⏱️ 45 – 55 min | ✅ Validation (NEW)
Exercises
Exercise 1: isalpha

Create:

"Python"


Check if it contains only letters

Print the result

Create:

"Python3"


Check again

Exercise 2: isnumeric

Create:

"12345"


Check if it contains only numbers

Create:

"12a45"


Check again

Exercise 3: User input validation (NO IF)

Ask the user to enter something:

Print:

whether it is alphabetic

whether it is numeric

🧠 Goal: understand input quality

⏱️ 55 – 60 min | Final Mini-Challenge

Ask the user for a sentence and print:

cleaned (strip)

lowercase

uppercase

length

whether it starts with a chosen word

whether it contains only letters

whether it contains only numbers

👉 You do not interpret — just display results.

## String practicce - normal

Exercise 1

Create this string:

"   Hello World   "


Remove spaces from the left

Remove spaces from the right

Remove spaces from both sides

Print each result.

Exercise 2

Create:

"PyThOn"


Convert to lowercase

Convert to uppercase

🔍 Search in Strings (NEW)
Exercise 3 — startswith()

Create:

"python programming"


Check if it starts with "python"

Print the result

Exercise 4 — endswith()

Using the same string:

Check if it ends with "programming"

Print the result

Exercise 5 — find()

Create:

"I love python"


Find the position of "python"

Print the result

👉 Observe what number you get.

Exercise 6 — in

Check and print:

"a" in "cat"

"z" in "cat"

✅ Validation (NEW)
Exercise 7 — isalpha()

Create:

"Python"


Check if it contains only letters

Print the result

Create:

"Python3"


Check again

Exercise 8 — isnumeric()

Create:

"12345"


Check if it contains only numbers

Print the result

Create:

"12a45"


Check again

Exercise 9 — User input validation

Ask the user to enter something.

Print:

whether it is alphabetic

whether it is numeric

(No decisions yet — just print results.)

🔹 Mixed Practice (Combine what you know)
Exercise 10

Ask the user for a word.
Then:

Remove spaces

Convert to lowercase

Print the length

Check if it starts with a specific letter

Check if it contains only letters

Exercise 11

Create:

"   Data Science 2024   "


Strip spaces

Convert to uppercase

Find "Science"

Check if the string is numeric

Exercise 12 — Observation exercise

Create:

"hello123"


Print:

isalpha()

isnumeric()

👉 Write down why the results are what they are (in plain English).

✅ What these exercises are teaching you (quietly)

How to inspect text

How to search inside text

How to validate user input

How booleans (True / False) behave

You’re building the foundation for real programs.
"""